### ISSUE TITLE
Youtube Emojis just result in the message containing the emoji id

### ISSUE THREAD

**Issue by Johnnycyan** [ixnoahlive/youtube-websocket#2]
When a user on youtube uses a youtube emoji the resulting message just contains the data-emoji-id as that part of the message.

Example: `UCkszU2WH9gy1mb0dV-11UJg/KsIfY6LzFoLM6AKanYDQAg`

And in the actual youtube website that emoji is:
```
<img class="emoji yt-formatted-string style-scope yt-live-chat-text-message-renderer" src="https://yt3.ggpht.com/cktIaPxFwnrPwn-alHvnvedHLUJwbHi8HCK3AgbHpphrMAW99qw0bDfxuZagSY5ieE9BBrA=w24-h24-c-k-nd" alt="face-blue-smiling" data-emoji-id="UCkszU2WH9gy1mb0dV-11UJg/KsIfY6LzFoLM6AKanYDQAg" shared-tooltip-text=":face-blue-smiling:" id="emoji-24">
```

**Comment by ixnoahlive** [comment]
What's the behaviour you'd like here? We're not exactly returning HTML and mostly just plaintext, I could add a "html" output parameter to this if you'd like that replaces this with the emoji html but i'm not sure what you exactly want me to do

**Comment by Johnnycyan** [comment]
> What's the behaviour you'd like here? We're not exactly returning HTML and mostly just plaintext, I could add a "html" output parameter to this if you'd like that replaces this with the emoji html but i'm not sure what you exactly want me to do

Well from what I can gather from a friend of mine, the way the normal innertube api works is it gives you a json list of "runs" that are either text or emoji and from that you can compile a full message. So, is there a way that you could provide this full set of "runs" on every message? He doesn't use a wrapper like youtube.js so I'm not sure it's possible this way.

An example api output he sent me:
```
"message": {
      "runs": [
          {
              "text": "Voting is only available on Twitch, friendos "
          },
          {
              "emoji": {
                  "emojiId": "UCkszU2WH9gy1mb0dV-11UJg/egJ1XufTKYfegwOo57ewAg",
                  "shortcuts": [
                      ":shelterin:"
                  ],
                  "searchTerms": [
                      "shelterin"
                  ],
                  "image": {
                      "thumbnails": [
                          {
                              "url": "https://yt3.ggpht.com/gjC5x98J4BoVSEPfFJaoLtc4tSBGSEdIlfL2FV4iJG9uGNykDP9oJC_QxAuBTJy6dakPxVeC=w24-h24-c-k-nd",
                              "width": 24,
                              "height": 24
                          },
                          {
                              "url": "https://yt3.ggpht.com/gjC5x98J4BoVSEPfFJaoLtc4tSBGSEdIlfL2FV4iJG9uGNykDP9oJC_QxAuBTJy6dakPxVeC=w48-h48-c-k-nd",
                              "width": 48,
                              "height": 48
                          }
                      ],
                      "accessibility": {
                          "accessibilityData": {
                              "label": "shelterin"
                          }
                      }
                  },
                  "isCustomEmoji": true
              }
          }
      ]
  },
  ```

**Comment by Johnnycyan** [comment]
He also sent me this relevant section of the youtube.js code that seems to process these runs for emojis
https://github.com/LuanRT/YouTube.js/blob/4fca6c354e5493c4d78802a813f7aa51ef0e2742/src/parser/classes/misc/EmojiRun.ts

**Comment by Johnnycyan** [comment]
Also, as far as the normal plaintext return goes, it would probably be ideal to just remove emoji data completely from it cause having a normal message and then randomly `UCkszU2WH9gy1mb0dV-11UJg/KsIfY6LzFoLM6AKanYDQAg` in the middle of it doesn't really make any sense.

**Comment by ixnoahlive** [comment]
Gotcha, not really working on this rn (school and work) so if you want to PR it I'll gladly approve but if I have some off time I'll look into it
